source("src/kenya-itt/setup.R")
source("config/kenya-itt/credentials.R")
source("src/kenya-itt/metadata.R")
source("src/kenya-itt/extract.R")
source("src/kenya-itt/transform-load-reports.R")
source("src/kenya-itt/fp-results-elt.R")
source("src/kenya-itt/imm_results_elt.R")
source("src/kenya-itt/malaria-results-elt.R")
source("src/kenya-itt/nutrition_results_elt.R")
source("src/kenya-itt/imm_administered_elt.R")
# source("src/kenya-itt/estimates.R")
